# params.yaml
base:
  project_name: "IEEE_CIS_Fraud_detection"

data_ingestion:
  test_size: 0.1
  random_state: 6

model_training:
  test_size: 0.13
  random_state: 6
  target_column: "isFraud"

mlflow:
  experiment_name: "IEEE-CIS-Fraud-Detection"
  tracking_uri: "mlruns"
  log_models: true

model_params:
  XGBClassifier:
    objective: binary:logistic
    eval_metric: auc
    tree_method: hist
    device: cuda
    scale_pos_weight: 27
    max_depth: 8
    min_child_weight: 5
    learning_rate: 0.02
    n_estimators: 3000
    subsample: 0.8
    colsample_bytree: 0.7
    reg_alpha: 1
    reg_lambda: 2
    early_stopping_rounds: 80

raw_data_cols:
  len: 
  features: 

